---
# vars file for roles/aws-cli

# AWS Configure
#aws_system_user: glauber.fonseca
#aws_profile: default
#access_key_id: xxxxxxxxxxxxxxxxxxx
#secret_access_key: xxxxxxxxxxxxxxx
#aws_region: us-east-1
#aws_format: json

# Adicionar linhas de configuração no .bashrc
bashrc:
  - echo '' >> /home/glauber/.bashrc
  - echo '# AWSGO, ALOG e HISTORY_TIME' >> /home/glauber/.bashrc
  - echo 'awsgo() { /usr/bin/ssh -i /home/glauber/.ssh/id_rsa_opsworks_glauberfonseca glauberfonseca@"$@";}' >> /home/glauber/.bashrc
  - echo 'alog() { /usr/bin/ssh glauber.fonseca@10.5.9."$@";}' >> /home/glauber/.bashrc
  - echo 'HISTTIMEFORMAT="%d/%m/%y %T "' >> /home/glauber/.bashrc

# ssh-copy-id
#sshcopyid:
#  - ssh-copy-id -i /home/mcnd2/.ssh/debiandesk_id_rsa glauber@192.168.0.115