---
- name: Atualizando Repositorios
  apt:
    update-cache: yes
  tags: add_repo

- name: Adicionando Repositorio Flathub Flatpak
  flatpak_remote:
    executable: "flatpak"
    name: flathub
    state: present
    flatpakrepo_url: "{{ flatpakrepo_url }}"
    method: system
  tags: add_repo

#- name: Instalacao GPG-Key
#  apt_key:
#    keyserver: keyserver.ubuntu.com
#    id: "{{ item }}"
#  loop: "{{ id_gpg }}"
#  tags: add_repo

- name: Adicionando Keys para Validacao dos Repositorios de Terceiros
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ apt_key_urls }}"
  tags: add_repo

- name: Adicionando dos Repositorios de Terceiros
  apt_repository:
    repo: "{{ item.url }}"
    state: present
    filename: "{{ item.filename }}"
    mode: '0644'
    update_cache: no
  loop: "{{ apt_repo_urls }}"
  tags: add_repo

- name: Atualizando Repositorios
  apt:
    update-cache: yes
  tags: add_repo

- name: Adicionando Token do Malwarebytes
  become: true
  shell: ACCOUNTTOKEN="{{ token_mblinux }}"
  #shell: ACCOUNTTOKEN=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  tags: add_repo
