---
# vars file for install-app

apps:
  - terminator
  - htop
  - hardinfo
  - lshw-gtk
  - gsmartcontrol
  - gparted
  - psensor
  - filezilla
  - remmina
  - gimp
  - flameshot
  - hplip-gui
  - pdfarranger #editar PDFs
  - xournal #"rabiscar" apresentação em slides
  - tldr
  - cmatrix
  - p7zip-rar
  - unrar
  - unrar-free
  - deborphan
  - google-chrome-stable
  - code
  - anydesk
  - atom
  - ansible
  - python3-pip
  - whois #contem o mkpassd
  - ethstatus
  - s-tui
  - libgconf-2-4 #dependencia para o forticlient
  - mblinux #Malwarebytes

flatpak_apps:
  - com.getpostman.Postman
  - com.jgraph.drawio.desktop

fc_dep_url: # VPN FortiClient e dependencias
  - http://ftp.de.debian.org/debian/pool/main/libi/libindicator/libindicator7_0.5.0-4_amd64.deb
  - http://ftp.de.debian.org/debian/pool/main/liba/libappindicator/libappindicator1_0.4.92-7_amd64.deb
  #- https://links.fortinet.com/forticlient/deb/vpnagent/forticlient_vpn_7.0.0.0018_amd64.deb # erro de assinatura ao instalar via playbook.

  ## Fonte: https://gist.github.com/WazeHell/0e1e55f2e414ffbaba6afb97f9c3ab96
  - https://filestore.fortinet.com/forticlient/downloads/forticlient_vpn_7.0.0.0018_amd64.deb

create_list_deb_fc:
  - ls -d /tmp/libindicator7_0.5.0-4_amd64.deb > /tmp/forticlient-main-deb.txt
  - ls -d /tmp/libappindicator1_0.4.92-7_amd64.deb >> /tmp/forticlient-main-deb.txt
  - ls -d /tmp/forticlient_vpn_7.0.0.0018_amd64.deb >> /tmp/forticlient-main-deb.txt

#deb_apps:
#  - https://github.com/meetfranz/franz/releases/download/v5.8.0/franz_5.8.0_amd64.deb #Franz
#  Note: para instalar Franz no Debian 11, deverá instalar o pacote de dependência
#  'libappindicator3-1' da versão unstable.