---
# vars file for add-repo

apt_key_urls:
  - https://dl.google.com/linux/linux_signing_key.pub #GoogleChrome
  - https://packages.microsoft.com/keys/microsoft.asc #VSCode
  - https://keys.anydesk.com/repos/DEB-GPG-KEY #AnyDesk
  - https://packagecloud.io/AtomEditor/atom/gpgkey #Atom
  - https://repositories.mwbsys.com/dpkg/keyring.gpg #Malwarebytes

#id_gpg:
#  - 2FAB19E7CCB7F415 #OpenFortiGUI exemplo

apt_repo_urls:
  - url: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main #GoogleChrome
    filename: google-chrome
  - url: deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main #VSCode
    filename: vscode
  - url: deb http://deb.anydesk.com/ all main #Anydesk
    filename: anydesk
  - url: deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main #Atom
    filename: atom
  - url: deb [arch=amd64] https://repositories.mwbsys.com/dpkg xenial non-free #Malwarebytes
    filename: malwarebytes

flatpakrepo_url:
  - url: https://dl.flathub.org/repo/flathub.flatpakrepo #Flathub

token_mblinux:
  #- sudo ACCOUNTTOKEN=xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  - xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
